version: '3.1'

services:
  db:
    image: postgres:10.12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: qareer
      POSTGRES_USER: qareer
      POSTGRES_DB: qareer
    ports:
      - 5432:5432
    volumes:
      - ./initdb/qareer.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: 
      context: .
      dockerfile: dev.dockerfile
    restart: always
    depends_on:
      - db
    environment:
      PORT: :3000
      DB_DRIVER: pgx
      DB_HOST: db
      DB_USER: qareer
      DB_PASSWORD: qareer
      DB_NAME: qareer
    ports:
      - 3000:3000
    volumes:
      - ./:/app
